services:
  - type: web
    name: cineflix-json-server
    env: node
    buildCommand: "npm install"
    startCommand: "npx json-server --watch db.json --host 0.0.0.0 --port $PORT"
    envVars:
      - key: NODE_ENV
        value: production
